all: p1 p2 p3 p4 p5
CC=g++

CFLAGS=-g -Wall

p1: assignment1_problem1.cpp
	$(CC) $(CFLAGS) -o p1.o assignment1_problem1.cpp


p2: testStack.cpp
	$(CC) $(CFLAGS) -o p2.o testStack.cpp

p3: LinkedList.cpp
	$(CC) $(CFLAGS) -o p3.o LinkedList.cpp

p4: assignment1_problem4.cpp
	$(CC) $(CFLAGS) -o p4.o assignment1_problem4.cpp

p5: assignment1_problem5.cpp
	$(CC) $(CFLAGS) -o p5.o assignment1_problem5.cpp


clean:
	$(RM) p1.o p2.o p3.o p4.o p5.o

	
	
	
